export const ADD_DATAVUZIX = "ADD_DATAVUZIX";
export const DATAVUZIX_LOADING = "DATAVUZIX_LOADING";
export const DATAVUZIX_FALIED = "DATAVUZIX_FALIED";

export const ADD_INIT_MAPFILTER = "ADD_INIT_MAPFILTER";
export const MAPFILTER_LOADING = "MAPFILTER_LOADING";
export const MAPFILTER_FAILED = "MAPFILTER_FAILED";
export const EDIT_MAPFILTER = "EDIT_MAPFILTER";

export const ADD_DETAILDIVDATA = "ADD_DETAILDIVDATA"
export const DETAILDIVDATA_LOADING = "DETAILDIVDATA_LOADING"
export const DETAILDIVDATA_FAILED = "DETAILDIVDATA_FAILED"

export const ADD_ADDRESSVALUE = "ADD_ADDRESSVALUE"
export const ADDRESSVALUE_LOADING = "ADDRESSVALUE_LOADING"
export const ADDRESSVALUE_FAILED = "ADDRESSVALUE_FAILED"