export const ADD_DATAVUZIX = "ADD_DATAVUZIX";
export const DATAVUZIX_LOADING = "DATAVUZIX_LOADING";
export const DATAVUZIX_FALIED = "DATAVUZIX_FALIED";

export const ADD_INIT_MAPFILTER = "ADD_INIT_MAPFILTER";
export const MAPFILTER_LOADING = "MAPFILTER_LOADING"; 
export const MAPFILTER_FAILED = "MAPFILTER_FAILED";
export const EDIT_MAPFILTER = "EDIT_MAPFILTER";